import { bigint, index, integer, pgTable, serial, text } from 'drizzle-orm/pg-core';

export const consoleRequests = pgTable('console_requests', {
  requestId: text('request_id').primaryKey(),
  createdAt: bigint('created_at', { mode: 'number' }).notNull(),
  routePrefix: text('route_prefix').notNull(),
  upstreamType: text('upstream_type').notNull().default('anthropic'),
  method: text('method').notNull(),
  path: text('path').notNull(),
  targetUrl: text('target_url').notNull(),
  requestModel: text('request_model').notNull(),
  apiKeyId: text('api_key_id'),
  apiKeyName: text('api_key_name'),
  originalPayload: text('original_payload'),
  originalPayloadTruncated: integer('original_payload_truncated').notNull().default(0),
  originalSummaryJson: text('original_summary_json'),
  forwardedPayload: text('forwarded_payload'),
  forwardedPayloadTruncated: integer('forwarded_payload_truncated').notNull().default(0),
  forwardedSummaryJson: text('forwarded_summary_json'),
  originalHeadersJson: text('original_headers_json'),
  forwardHeadersJson: text('forward_headers_json'),
  responseHeadersJson: text('response_headers_json'),
  responseStatus: integer('response_status'),
  responseStatusText: text('response_status_text'),
  responsePayload: text('response_payload'),
  responsePayloadTruncated: integer('response_payload_truncated').notNull().default(0),
  responsePayloadTruncationReason: text('response_payload_truncation_reason'),
  responseBodyBytes: integer('response_body_bytes').notNull().default(0),
  firstChunkAt: bigint('first_chunk_at', { mode: 'number' }),
  firstTokenAt: bigint('first_token_at', { mode: 'number' }),
  completedAt: bigint('completed_at', { mode: 'number' }),
  hasStreamingContent: integer('has_streaming_content').notNull().default(0),
  responseModel: text('response_model'),
  stopReason: text('stop_reason'),
  inputTokens: integer('input_tokens').notNull().default(0),
  outputTokens: integer('output_tokens').notNull().default(0),
  totalTokens: integer('total_tokens').notNull().default(0),
  cacheCreationInputTokens: integer('cache_creation_input_tokens').notNull().default(0),
  cacheReadInputTokens: integer('cache_read_input_tokens').notNull().default(0),
  cachedInputTokens: integer('cached_input_tokens').notNull().default(0),
  reasoningOutputTokens: integer('reasoning_output_tokens').notNull().default(0),
  ephemeral5mInputTokens: integer('ephemeral_5m_input_tokens').notNull().default(0),
  ephemeral1hInputTokens: integer('ephemeral_1h_input_tokens').notNull().default(0),
  failoverFrom: text('failover_from'),
  failoverChainJson: text('failover_chain_json'),
  originalRoutePrefix: text('original_route_prefix'),
  originalRequestModel: text('original_request_model'),
  failoverReason: text('failover_reason'),
  sourceRequestType: text('source_request_type').notNull().default('unknown'),
  tokenUsageEstimated: integer('token_usage_estimated').notNull().default(0),
}, (table) => ({
  createdAtIdx: index('idx_console_requests_created_at').on(table.createdAt),
  compareIdx: index('idx_console_requests_compare').on(
    table.routePrefix,
    table.method,
    table.path,
    table.requestModel,
    table.createdAt,
  ),
  routePrefixIdx: index('idx_console_requests_route_prefix').on(table.routePrefix, table.createdAt),
  responseModelIdx: index('idx_console_requests_response_model').on(table.responseModel, table.createdAt),
}));

export const consoleApiKeys = pgTable('console_api_keys', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  keyHash: text('key_hash').notNull(),
  keyValue: text('key_value').notNull(),
  prefix: text('prefix').notNull(),
  createdAt: bigint('created_at', { mode: 'number' }).notNull(),
  lastUsedAt: bigint('last_used_at', { mode: 'number' }),
  revoked: integer('revoked').notNull().default(0),
  allowedModelsJson: text('allowed_models_json').notNull().default('[]'),
}, (table) => ({
  keyHashIdx: index('idx_console_api_keys_key_hash').on(table.keyHash),
  createdAtIdx: index('idx_console_api_keys_created_at').on(table.createdAt),
}));

export const consoleProviders = pgTable('console_providers', {
  channelName: text('channel_name').primaryKey(),
  providerUuid: text('provider_uuid').notNull().default(''),
  type: text('type').notNull(),
  targetBaseUrl: text('target_base_url').notNull(),
  systemPrompt: text('system_prompt'),
  modelsJson: text('models_json').notNull().default('[]'),
  priority: integer('priority').notNull().default(0),
  authHeader: text('auth_header'),
  authValue: text('auth_value'),
  extraFieldsJson: text('extra_fields_json').notNull().default(''),
  enabled: integer('enabled').notNull().default(1),
  createdAt: bigint('created_at', { mode: 'number' }).notNull(),
  updatedAt: bigint('updated_at', { mode: 'number' }).notNull(),
}, (table) => ({
  createdAtIdx: index('idx_console_providers_created_at').on(table.createdAt),
  updatedAtIdx: index('idx_console_providers_updated_at').on(table.updatedAt),
}));

export const modelAliases = pgTable('model_aliases', {
  id: serial('id').primaryKey(),
  alias: text('alias').notNull().unique(),
  provider: text('provider').notNull(),
  model: text('model').notNull(),
  description: text('description'),
  enabled: integer('enabled').notNull().default(1),
  createdAt: bigint('created_at', { mode: 'number' }).notNull(),
  updatedAt: bigint('updated_at', { mode: 'number' }).notNull(),
}, (table) => ({
  aliasIdx: index('idx_model_aliases_alias').on(table.alias),
  createdAtIdx: index('idx_model_aliases_created_at').on(table.createdAt),
}));

export const modelCatalogCache = pgTable('model_catalog_cache', {
  modelId: text('model_id').primaryKey(),
  contextWindow: integer('context_window'),
  pricingJson: text('pricing_json'),
  fetchedAt: bigint('fetched_at', { mode: 'number' }).notNull(),
});
