export const PAYLOAD_LOG_LIMIT_BYTES = 5 * 1024 * 1024;

export const RESPONSE_STREAM_LOG_MAX_DURATION_MS_ENV = 'CONSOLE_STREAM_LOG_MAX_DURATION_MS';

export const DEFAULT_RESPONSE_STREAM_LOG_MAX_BYTES = PAYLOAD_LOG_LIMIT_BYTES;
export const DEFAULT_RESPONSE_STREAM_LOG_MAX_DURATION_MS = 1_800_000;

export const MIN_RESPONSE_STREAM_LOG_MAX_DURATION_MS = 100;
